/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adrian.c_ruleta_noexamen;

/**
 *
 * @author FP
 */
public class Ruleta extends javax.swing.JFrame {

    /**
     * Creates new form Ruleta
     */
    public Ruleta() {
        initComponents();
        buttonGroup1.add(botonRojo);
        buttonGroup1.add(botonNegro);
        buttonGroup1.add(botonVerde);
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textoDineroApostado = new javax.swing.JTextField();
        checkBoxApostar = new javax.swing.JCheckBox();
        botonApostar = new javax.swing.JButton();
        botonRojo = new javax.swing.JRadioButton();
        botonNegro = new javax.swing.JRadioButton();
        botonVerde = new javax.swing.JRadioButton();
        numeroSelecionado = new javax.swing.JLabel();
        labelDinero = new javax.swing.JLabel();
        botonInstrucciones = new javax.swing.JButton();
        botonComprar = new javax.swing.JButton();

        jLabel1.setText("DINERO :");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ruleta1.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoDineroApostado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel2.add(textoDineroApostado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1027, 9, 167, 94));

        checkBoxApostar.setText("Seguro de apostar");
        checkBoxApostar.setActionCommand("");
        jPanel2.add(checkBoxApostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1027, 112, -1, -1));

        botonApostar.setBackground(new java.awt.Color(51, 51, 51));
        botonApostar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonApostar.setText("APOSTAR");
        botonApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonApostarActionPerformed(evt);
            }
        });
        jPanel2.add(botonApostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1027, 172, 167, 46));

        botonRojo.setBackground(new java.awt.Color(255, 0, 0));
        botonRojo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonRojo.setText("ROJO(pares)");
        botonRojo.setOpaque(true);
        jPanel2.add(botonRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 109, 147, -1));

        botonNegro.setBackground(new java.awt.Color(0, 0, 0));
        botonNegro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonNegro.setText("NEGRO(impares)");
        jPanel2.add(botonNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 109, -1, -1));

        botonVerde.setBackground(new java.awt.Color(51, 204, 0));
        botonVerde.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonVerde.setText("VERDE(0)");
        jPanel2.add(botonVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 109, 117, -1));

        numeroSelecionado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numeroSelecionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroSelecionado.setText("jLabel4");
        jPanel2.add(numeroSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 40, 167, -1));

        labelDinero.setText("DINERO");
        jPanel2.add(labelDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, 239, 43));

        botonInstrucciones.setBackground(new java.awt.Color(51, 51, 51));
        botonInstrucciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonInstrucciones.setText("INSTRUCCIONES");
        botonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstruccionesActionPerformed(evt);
            }
        });
        jPanel2.add(botonInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 172, 157, 46));

        botonComprar.setBackground(new java.awt.Color(51, 51, 51));
        botonComprar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonComprar.setText("COMPRAR FICHAS");
        jPanel2.add(botonComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 109, -1, 49));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonApostarActionPerformed
        
       int dineroApostado=Integer.parseInt(textoDineroApostado.getText());
       int dineroActual=Integer.parseInt(textoDineroApostado.getText());
        if (checkBoxApostar.isSelected()||dineroActual>0) {
            jugar();
            
        }
    }//GEN-LAST:event_botonApostarActionPerformed

    private void botonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstruccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInstruccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ruleta().setVisible(true);
            }
        });
    }
    
    private void jugarRuleta(int dinero, int dineroActual){
        
        int numneroElegido=(int)(Math.random()*37);
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonApostar;
    private javax.swing.JButton botonComprar;
    private javax.swing.JButton botonInstrucciones;
    private javax.swing.JRadioButton botonNegro;
    private javax.swing.JRadioButton botonRojo;
    private javax.swing.JRadioButton botonVerde;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBoxApostar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelDinero;
    private javax.swing.JLabel numeroSelecionado;
    private javax.swing.JTextField textoDineroApostado;
    // End of variables declaration//GEN-END:variables
}
