/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tema2grafico;

import java.sql.*;
import java.awt.Color;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

/**
 *
 * @author FP
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonAcceder1 = new javax.swing.JButton();
        panelIzquierda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelDerecha = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        botonAcceder = new javax.swing.JButton();
        botonCrear = new javax.swing.JButton();
        textoErrorCrear = new javax.swing.JLabel();
        botonRestablecer = new javax.swing.JButton();
        textoConstraseña = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(96, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        botonAcceder1.setBackground(new java.awt.Color(153, 153, 153));
        botonAcceder1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        botonAcceder1.setForeground(new java.awt.Color(0, 0, 0));
        botonAcceder1.setText("ACCEDER");
        botonAcceder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcceder1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelIzquierda.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\FP\\Documents\\NetBeansProjects\\Interfazes\\Tema2Grafico\\img\\arkham.png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout panelIzquierdaLayout = new javax.swing.GroupLayout(panelIzquierda);
        panelIzquierda.setLayout(panelIzquierdaLayout);
        panelIzquierdaLayout.setHorizontalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelIzquierdaLayout.setVerticalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDerecha.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTRASEÑA");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel3.setBackground(new java.awt.Color(0, 153, 204));
        jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USUARIO");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jLabel3.setVerifyInputWhenFocusTarget(false);

        textoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoUsuarioMouseClicked(evt);
            }
        });

        botonAcceder.setBackground(new java.awt.Color(153, 153, 153));
        botonAcceder.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        botonAcceder.setForeground(new java.awt.Color(0, 0, 0));
        botonAcceder.setText("ACCEDER");
        botonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAccederActionPerformed(evt);
            }
        });

        botonCrear.setBackground(new java.awt.Color(153, 153, 153));
        botonCrear.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        botonCrear.setForeground(new java.awt.Color(0, 0, 0));
        botonCrear.setText("CREAR USUARIO");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        textoErrorCrear.setBackground(new java.awt.Color(51, 51, 51));
        textoErrorCrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoErrorCrear.setForeground(new java.awt.Color(51, 51, 51));
        textoErrorCrear.setText("Registro no valido o ya está en la base de datos");
        textoErrorCrear.setFocusable(false);

        botonRestablecer.setBackground(new java.awt.Color(153, 153, 153));
        botonRestablecer.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        botonRestablecer.setForeground(new java.awt.Color(0, 0, 0));
        botonRestablecer.setText("RESTABLECER");
        botonRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestablecerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDerechaLayout = new javax.swing.GroupLayout(panelDerecha);
        panelDerecha.setLayout(panelDerechaLayout);
        panelDerechaLayout.setHorizontalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDerechaLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoUsuario))
                    .addGroup(panelDerechaLayout.createSequentialGroup()
                        .addComponent(textoErrorCrear)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDerechaLayout.createSequentialGroup()
                        .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCrear))
                        .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDerechaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(botonAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addGroup(panelDerechaLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(textoConstraseña)))))
                .addContainerGap())
        );
        panelDerechaLayout.setVerticalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDerechaLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerechaLayout.createSequentialGroup()
                        .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(textoConstraseña))
                .addGap(58, 58, 58)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(textoErrorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoUsuarioMouseClicked
        textoUsuario.setText("");
        textoUsuario.setForeground(Color.black);
    }//GEN-LAST:event_textoUsuarioMouseClicked

    private void botonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAccederActionPerformed
        String usuario = textoUsuario.getText().toString();
      
        try {
           
             accederSQL(usuario, getMD5(new String(textoConstraseña.getPassword())));
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_botonAccederActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
       
        JFRAMEcrear jc=new JFRAMEcrear();
        jc.setVisible(true);
        jc.setEnabled(true);
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonAcceder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcceder1ActionPerformed
       
    }//GEN-LAST:event_botonAcceder1ActionPerformed

    private void botonRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestablecerActionPerformed
      String usuario = textoUsuario.getText().toString();
      
        try {
             restablecerContraseña(usuario, getMD5(new String(textoConstraseña.getPassword())));
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_botonRestablecerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    public void accederSQL(String usuario, String contraseña) {
               

        try {

            String url = "jdbc:mysql://localhost:3306/ejercicioBBDDInterfaces";
            String user = "root";
            String password = "Mijefa1704";
            Connection con = DriverManager.getConnection(url, user, password);
            System.out.println("Conexion correcta");

            String buscar = "SELECT * FROM personas WHERE usuario= ? AND contraseña=?";
            PreparedStatement sentenciaBuscar = con.prepareStatement(buscar);
            sentenciaBuscar.setString(1, usuario);
            sentenciaBuscar.setString(2, contraseña);
            boolean esta = false;
            String nombreBD = "";
            String contraseñaBD = "";
            ResultSet rs = sentenciaBuscar.executeQuery();
            while (rs.next()) {

                nombreBD = rs.getString("usuario");
                contraseñaBD = rs.getString("contraseña");

                if (nombreBD.equals(usuario) || contraseñaBD.equals(contraseña)) {
                    esta = true;
                }

            }
            if (esta) {
                System.out.println("Esta usuario");
               JFRAMEAccede ja=new JFRAMEAccede();
               ja.setEnabled(true);
               ja.setVisible(true);
               this.dispose();
             
            } else {
               textoErrorCrear.setText("Usuario no encontrado");
               textoErrorCrear.setForeground(Color.red);
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }

    public void registrarSQL(String usuario, String contraseña) throws SQLException {
        String url = "jdbc:mysql://localhost:3306/ejercicioBBDDInterfaces";
        String user = "root";
        String password = "Mijefa1704";
        try {
            Connection con = DriverManager.getConnection(url, user, password);
            System.out.println("Conexion correcta");
            String insert = "INSERT INTO personas VALUES(?,?)";
            PreparedStatement senteciaInsertar = con.prepareStatement(insert);
            senteciaInsertar.setString(1, usuario);
            senteciaInsertar.setString(2, contraseña);
            senteciaInsertar.execute();
            System.out.println("Registro insertado");
            textoErrorCrear.setText("Usuario registrado");
            textoErrorCrear.setForeground(Color.green);
        } catch (SQLException ex) {
         textoErrorCrear.setForeground(Color.red);
            System.out.println(ex.getMessage());
        }

    }
    
    public void restablecerContraseña(String usuario,String contraseña){
        
           String url = "jdbc:mysql://localhost:3306/ejercicioBBDDInterfaces";
        String user = "root";
        String password = "Mijefa1704";
        try {
            Connection con = DriverManager.getConnection(url, user, password);
            System.out.println("Conexion correcta");
            String update="UPDATE personas SET contraseña=? WHERE usuario=? "; 
            PreparedStatement senteciaUpdate=con.prepareStatement(update);
            senteciaUpdate.setString(2, usuario);
            senteciaUpdate.setString(1, contraseña);
            senteciaUpdate.execute();
            
            textoErrorCrear.setText("SE HA RESTABLECIDO LA CONTRASEÑA");
            textoErrorCrear.setForeground(Color.green);
            
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }
    
public static String getMD5(String input) {
 try {
 MessageDigest md = MessageDigest.getInstance("MD5");
 byte[] messageDigest = md.digest(input.getBytes());
 BigInteger number = new BigInteger(1, messageDigest);
 String hashtext = number.toString(16);

 while (hashtext.length() < 32) {
 hashtext = "0" + hashtext;
 }
 return hashtext;
 }
 catch (NoSuchAlgorithmException e) {
 throw new RuntimeException(e);
 }
 }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAcceder;
    private javax.swing.JButton botonAcceder1;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonRestablecer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JPasswordField textoConstraseña;
    private javax.swing.JLabel textoErrorCrear;
    private javax.swing.JTextField textoUsuario;
    // End of variables declaration//GEN-END:variables
}
